batch_size: 128
test_batch_size: 128
epochs: 10
lr: 0.1
momentum: 0.9
no_cuda: False
seed: 1
log_interval: 10
optim: sgd
dmom: 0.5
low_theta: 1e-5
high_theta: 1e5
arch: resnet32
workers: 4
weight_decay: 1e-4
dmom_interval: 1
dmom_temp: 0
alpha: normg
