data: ./data/rcv1
batch_size: 128
test_batch_size: 1000
epochs: 50
lr: 0.01
momentum: 0.9
no_cuda: False
seed: 1
log_interval: 10
optim: sgd
arch: None
workers: 10
weight_decay: 5.e-4
train_accuracy: True
log_image: False
lr_decay_epoch: 30
num_class: 2
dim: 47236
