data: none
batch_size: 64
test_batch_size: 1000
epochs: 50
lr: 0.01
momentum: 0.5
no_cuda: False
seed: 1
log_interval: 10
optim: sgd
dmom: 0.5
low_theta: 1.e-5
high_theta: 1.e5
arch: None
workers: 2
weight_decay: 5.e-4
dmom_interval: 1
dmom_temp: 0
alpha: loss
num_train_data: 640
num_test_data: 10000
dim: 2
num_class: 5
c_const: 50
d_const: 10
sampler: False
train_accuracy: True
alpha_norm: none
sampler_weight: alpha_normed
#wmomentum: False
log_image: False
lr_decay_epoch: 100
norm_temp: 1
sampler_alpha_th: 0
sampler_alpha_perc: 0
sampler_w2c: linear2
sampler_max_count: 20
sampler_start_epoch: 1
g_update_start: 0
g_update_interval: 1
sampler_lr_update: False
sampler_lr_window: 40
divlen: 0
wmomentum: 0.5
sampler_repetition: False
exp_lr: False
corrupt_perc: 0
log_nex: False
lr_scale: False
sampler_maxw: 1
tblog_interval: 100
data_aug: False
wnoise: False
wnoise_stddev: 1.e-3
min_batches: 1
tauXstd: False
tauXstdL: False
scheduler: False
pretrained: False
nodropout: False
minvar: False
instantw: False
lr_decay_rate: 0.1
sma_momentum: 0.0
nesterov: False
log_stats: False
label_smoothing: 0
duplicate: 0,0
alpha_diff: False
gluster: False
g_ncluster: 10
g_beta: 0.999
g_min_size: 1
g_reinit: largest
gb_citers: 10
