data: ./data/cifar10
batch_size: 128
test_batch_size: 1000
epochs: 100
lr: 0.01
momentum: 0.9
no_cuda: False
seed: 1
log_interval: 10
optim: sgd
arch: cnn
workers: 10
weight_decay: 5.e-4
train_accuracy: True
log_image: True
lr_decay_epoch: 50
num_class: 100
