data: ./data/mnist
batch_size: 128
test_batch_size: 1000
epochs: 50
lr: 0.01
momentum: 0.5
no_cuda: False
seed: 1
log_interval: 10
optim: sgd
dmom: 0.5
low_theta: 1.e-5
high_theta: 1.e5
arch: mlp
workers: 2
weight_decay: 5.e-4
dmom_interval: 1
dmom_temp: 0
alpha: loss
sampler: False
train_accuracy: True
alpha_norm: none
sampler_weight: alpha_normed
#wmomentum: False
log_image: True
lr_decay_epoch: 30
norm_temp: 1
sampler_alpha_th: 0
sampler_alpha_perc: 0
sampler_w2c: linear2
sampler_max_count: 20
sampler_start_epoch: 1
g_update_start: 0
g_update_interval: 1
sampler_lr_update: False
sampler_lr_window: 40
divlen: 0
wmomentum: 0.5
sampler_repetition: False
exp_lr: False
num_class: 10
corrupt_perc: 0
log_nex: False
lr_scale: False
sampler_maxw: 1
tblog_interval: 100
data_aug: False
wnoise: False
wnoise_stddev: 1.e-3
min_batches: 1
tauXstd: False
scheduler: False
pretrained: False
nodropout: False
minvar: False
instantw: False
lr_decay_rate: 0.1
sma_momentum: 0.0
nesterov: False
log_stats: False
label_smoothing: 0
duplicate: 0,0
alpha_diff: False
gluster: False
gluster_num: 10
gluster_beta: 0.9
